
title: Pr치ctica 8 - Aplicaci칩n de procesamiento de notas de texto
author: Leonardo Dorta Bejarano
email: alu0101166230@ull.edu.es
description: se pretende realizar tendr치 que implementar una aplicaci칩n de procesamiento de notas de texto

github_username: alu0101166230

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman